### ISSUE TITLE
Add an argument to obtain git branch, insteaf of relying on GIT_BRANCH env var

### ISSUE THREAD

**Issue by jonhattan** [Metadrop/drupal-artifact-builder#14]
`getCurrentBranch()` method tries to guess current branch and fallbacks to `GIT_BRANCH` env var (set by jenkins) in case we're in a detached head state:

https://github.com/Metadrop/drupal-artifact-builder/blob/4360cdf25f987e7c3e84fb3e977baaaed155da1a/src/BaseCommand.php#L135-L139

This is a hidden feature, and dependant on a specific CI product (jenkins).

On the other hand, it is hard to impossible to use in a containerized setup:

 * In case we're generating the artifact from a docker container, we need to add `--env GIT_BRANCH=${GIT_BRANCH}` in order to provide the branch
 * In case of ddev, it is impossible to provide that at runtime

So I propose to remove dependency on GIT_BRANCH and provide a cli argument to optionally specify the branch.

**Comment by omarlopesino** [comment]
I agree that reading GIT_BRANCH is not neccesary and too dependent on Jenkins. The tool should not be coupled to any specific platform.

It is possible to add a parameter named `branch` that sets the branch. Example:

```
drupal-artifact builder git --repository=<repo> --branch=develop
```

If this parameter is empty, it is possible to guess the branch with `git branch --show-current`. If the branch is not found yet, then throw a exception.

I can work in it as soon as possible, PRs are welcome too.

**Comment by omarlopesino** [comment]
@jonhattan may you review this PR: https://github.com/Metadrop/drupal-artifact-builder/pull/15 ?

**Comment by jonhattan** [comment]
@omarlopesino I guess we're ready to remove GIT_BRANCH support.

**Comment by omarlopesino** [comment]
Done in 2.0.0-rc1
