### ISSUE TITLE
Make Git dependency optional at create command

### ISSUE THREAD

**Issue by omarlopesino** [Metadrop/drupal-artifact-builder#19]
Currently, artifact create command is checking that the code is not modified by git before creating it.

This gives problem when the artifact is being created in infrastructures that do not have git installed, and the create command should not need git.

Affected code: https://github.com/Metadrop/drupal-artifact-builder/blob/main/src/BaseCommand.php#L98

## Proposed resolution

For the create command, only check artifact content is clean when git is available. When git is not available, display a message indicating that git is not present, so this step is ommited.

Also, we should check if there is a repo available so that we only check content is clean when we are inside a repo

**Comment by rsanzante** [comment]
Should it also check there is a repo available? This should be easy, just check there's a .git folder.

**Comment by omarlopesino** [comment]
@rsanzante that's true, I have added it to the proposed resolution, thanks!

**Comment by juanjol** [comment]
I have added PR #20 to try to remedy this. Any comments or input would be welcome.

**Comment by omarlopesino** [comment]
Looks okay to me. I've just requested a minimal change.

Can you confirm that with this changes the problem you have had in your specific project is solved?

**Comment by juanjol** [comment]
I have just made the changes you requested Omar. It works ok for me.

**Comment by omarlopesino** [comment]
Merged, thanks! I've just released it at 2.0.2
