### ISSUE TITLE
Add a config file at project level to manage complex situations.

### ISSUE THREAD

**Issue by juanjol** [Metadrop/drupal-artifact-builder#6]
It would be useful to be able to add at project level a yml file in which to configure which files should not be in the artifact (for example to remove the core tests folder) or other types of files that composer brings by default, but that we do not want in the package to deploy.

My proposal would be that artifact-builder would be able to read a .yml file in the root of the project where it is deployed and be able to delete the marked paths. The file could be something like this:

```
remove:
  - folder1
  - folder2/.*
other-operations:
  - folder3
  - folder4
```

I think it is more useful a file to manage this than to put it in jenkins, so that at development level it is something fast, does not require to modify anything in jenkins, and it is also marked in the repository of the project.

**Comment by omarlopesino** [comment]
After a meeting it has been postponed to later as there isn't global consensus about:

- Is it a priority to have this functionality ASAP?
- Does this provide value for general Drupal projects or just for very specific ones?
- Can this functionality produce side effects as the system will allow to exclude files that are needed (for example)?

**Comment by jonhattan** [comment]
I think almost all currently open issues may be fixed with this feature.

* #7: solution: Allow user to exclude .gitignore
* #4: solution: same 
* #3: solution: Exclude sites/default/files by default. Don't rely on .gitignore

**Comment by omarlopesino** [comment]
Another issue: https://github.com/Metadrop/drupal-artifact-builder/issues/16

**Comment by omarlopesino** [comment]
I have been working on this today and now the latest version generates the artifact allowing the usage of a configuration file.

I have documented it at https://github.com/Metadrop/drupal-artifact-builder/?tab=readme-ov-file#configuration

Can you check the documentation is clear? cc @jorgetutor @lpeidro ?

**Comment by omarlopesino** [comment]
It has been reviewed and launched at version 2.0.0-alpha1. Closing.

Let's keep in mind  [this proposal](https://github.com/Metadrop/drupal-artifact-builder/issues/6#issuecomment-2362871601) for the other issues.
